platform :ios, '9.0'

target "LeafByte" do
  pod 'AppAuth', '~> 1.7.5'
  pod 'SwiftLint'
end
target 'LeafByteTests' do
  inherit! :search_paths
  pod 'AppAuth/Core'
end

inhibit_all_warnings!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end
